# Generated by Django 4.0.4 on 2022-06-29 12:51

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('isim_soyisim', models.CharField(max_length=150)),
                ('mesaj', models.TextField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişim',
                'db_table': 'iletisim',
            },
        ),
        migrations.CreateModel(
            name='KategoriModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders', models.CharField(max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='ders')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'db_table': 'kategori',
            },
        ),
        migrations.CreateModel(
            name='IlanlarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilan_baslik', models.CharField(max_length=50, verbose_name='İlan Başlığı')),
                ('konum', models.CharField(max_length=50, verbose_name='Konum')),
                ('okulu', models.CharField(max_length=150, verbose_name='Eğitim Seviyesi')),
                ('icerik', models.TextField(verbose_name='Detaylar')),
                ('fiyat', models.IntegerField(verbose_name='Ücret')),
                ('olus_tarih', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='ilan_baslik', unique=True)),
                ('ilan_sahibi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to=settings.AUTH_USER_MODEL, verbose_name='İlanı Veren')),
                ('kategoriler', models.ManyToManyField(related_name='ilan', to='ozelders.kategorimodel')),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
                'db_table': 'ilan',
            },
        ),
        migrations.CreateModel(
            name='BasvurModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilan_basvur', models.TextField(verbose_name='Tanıtım Yazısı')),
                ('basvur_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvurular', to='ozelders.ilanlarmodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvuru', to='account.teacher', verbose_name='Eğitmen')),
            ],
            options={
                'verbose_name': 'Başvuru',
                'verbose_name_plural': 'Başvurular',
                'db_table': 'basvuru',
                'ordering': ['basvur_tarihi'],
            },
        ),
    ]
