# Generated by Django 4.0.4 on 2022-06-29 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('ozelders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilanlarmodel',
            name='ilan_sahibi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to='account.student', verbose_name='İlanı Veren'),
        ),
    ]
