# Generated by Django 4.0.2 on 2022-02-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozelders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorimodel',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
    ]
