# Generated by Django 4.0.2 on 2022-02-23 17:14

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ozelders', '0002_alter_kategorimodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlanlarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilan_baslik', models.CharField(max_length=50, verbose_name='İlan Başlığı')),
                ('konum', models.CharField(max_length=50, verbose_name='Konum')),
                ('okulu', models.CharField(max_length=150, verbose_name='Eğitim Seviyesi')),
                ('icerik', models.TextField(verbose_name='Detaylar')),
                ('fiyat', models.IntegerField(verbose_name='Ücret Aralığı')),
                ('olus_tarih', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='ilan_baslik', unique=True)),
                ('ilan_sahibi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to=settings.AUTH_USER_MODEL, verbose_name='İlanı Veren')),
                ('kategoriler', models.ManyToManyField(related_name='ilan', to='ozelders.KategoriModel')),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
                'db_table': 'ilan',
            },
        ),
    ]
