# Generated by Django 4.0.2 on 2022-02-24 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ozelders', '0003_ilanlarmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasvurModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilan_basvur', models.TextField(verbose_name='Tanıtım Yazısı')),
                ('basvur_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvurular', to='ozelders.ilanlarmodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvuru', to=settings.AUTH_USER_MODEL, verbose_name='Eğitmen')),
            ],
            options={
                'verbose_name': 'Başvuru',
                'verbose_name_plural': 'Başvurular',
                'db_table': 'basvuru',
            },
        ),
    ]
