# Generated by Django 4.0.4 on 2022-07-03 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ozelders', '0004_alter_ilanlarmodel_fiyat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basvurmodel',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvuru', to=settings.AUTH_USER_MODEL, verbose_name='Eğitmen'),
        ),
        migrations.AlterField(
            model_name='ilanlarmodel',
            name='ilan_sahibi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to=settings.AUTH_USER_MODEL, verbose_name='İlanı Veren'),
        ),
    ]
