# Generated by Django 4.0.2 on 2022-02-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozelders', '0004_basvurmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basvurmodel',
            options={'ordering': ['basvur_tarihi'], 'verbose_name': 'Başvuru', 'verbose_name_plural': 'Başvurular'},
        ),
    ]
