# Generated by Django 4.0.2 on 2022-02-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ozelders', '0005_alter_basvurmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basvurmodel',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvuru', to='auth.group', verbose_name='Eğitmen'),
        ),
    ]
