# Generated by Django 4.0.2 on 2022-03-17 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('ozelders', '0008_iletisimmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basvurmodel',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvuru', to='account.teacher', verbose_name='Eğitmen'),
        ),
        migrations.AlterField(
            model_name='ilanlarmodel',
            name='ilan_sahibi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to='account.student', verbose_name='İlanı Veren'),
        ),
    ]
