# Generated by Django 4.0.2 on 2022-06-25 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ozelders', '0009_alter_basvurmodel_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilanlarmodel',
            name='fiyat',
            field=models.IntegerField(verbose_name='Ücret'),
        ),
        migrations.AlterField(
            model_name='ilanlarmodel',
            name='ilan_sahibi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to=settings.AUTH_USER_MODEL, verbose_name='İlanı Veren'),
        ),
    ]
